##########################
##
## Paige Levangie
## Master Thesis Project
## Interactive Tool: MURPH
## 
## Generate Script: Report "Output" Code
##
##########################

# Generate the code users will receive with their report
myCode <- paste0(
'#########################
## My Code
## Generated By MURPH
#########################
                  
#### Load Libraries ####
library(tidyverse)
library(ggplot2)
                 
#### Read Data ####

myData <- read.csv("put filepath here")

#### Custom Functions ####

# Create function to calculate variable mode
find_variablemode <- function(v) {
  # find all unique values in variable                
  unique_values <- unique(v)
  # determine frequency of unique values and return highest
  unique_values[which.max(tabulate(match(v, unique_values)))]
}

#### Statistics ####

# Create General Statistics Table
my_generalstats <- myData %>% 
  # Summarizes variable columns to display desired statistic values
  summarise_all(.funs = list(noe = compose(sum, compose("!", is.na)), # determines the number of elements 
                             sum = sum, # the sum of all values of the variable 
                             min = min, # the minimum value of the variable
                             mean = mean, # the mean of the variable 
                             median = median, # the median of the variable
                             mode = find_variablemode, # the mode of the variable
                             max = max, # the maximum value of the variable
                             sd = sd, # the standard deviation of the variable
                             variance = var, # the variance of the variable
                             iqr = IQR)) %>% # the inner-quartile range of the variable
  # these next few lines reformat the data into a more readable format
  gather(vars, vals) %>%     
  separate(vars, c("Variable", "stat")) %>% 
  spread(stat, vals) %>% 
  as.data.frame() %>% 
  # this rounds each numeric column to have 4 digits after the decimal
  mutate_if(is.numeric, round, digits = 4)

# view the table
my_generalstats')

## Write generated report output code into R script
writeChar(paste(myCode, collapse = "\n"), "report_mycode.R")