##########################
##
## Paige Levangie
## Master Thesis Project
## Interactive Tool: MURPH
## 
## Notes
##
##########################

#### Notes and reminders ####

# this is where I can write little notes for myself and put some code
# that doesn't really fit in anywhere that I don't want just delete yet


# from last work session
# I went through and added a bunch of stuff to the report generated by murph
# and moved it to it's own script - separate from the main server script
# got started on generating the r script for "my code" that comes with the report


# go through and possibly look at app organization and code organization again.
# might be easier to use outputs if contained within reactive functions rather
# than uiOutputs contained within eachother (changes where output id's and stuff are stored/accessed)


##### Darwin core stuff ####

# source the generate files in the global folder
#
# try and navigate how to automate reformatting data into darwin core format
# start to generate what each step will be and format the verification portion and setup section to that

## This code is for the outputs of the selected variable classes
## Based on the darwin core requirements for metadata documention

# They ALL need a detailed description - DONE

# Character: only require a short description
# Date: just a date format
# Numeric: unit and numbertype (may leave this out and have it automatically filled in if Interger is selected)
# Factor: need a definition and code for each factor level

#### variable verification stuff ####

# myData <- quakes %>% mutate(multiclass = rep(c(3,4,2,"5-test"), each = 250))
# str(myData)
# CHARACTER
# classcharacter <- function(i) {
 
#   # Update class
#   myData[, i] <- as.character(myData[, i])
# 
#   # Trim the whitespace on the string
#   str_trim(myData[, i], side = "both")
# 
#   # Set the changes made to the variable to the dataset in the global environment
#   .GlobalEnv$myData[, i] <- myData[, i]
# 
# }

# NUMERIC
# classnumeric <- function(i) {
# 
#   # Make a table to see if variable values can be numeric
#   classcheck <- table(is.na(as.numeric(as.character(myData[, i]))))
# 
#   if(TRUE %in% names(classcheck)) {
# 
#     # Make a table of all the rows where i isn't numeric
#     errortable <- myData %>% filter(is.na(as.numeric(as.character(myData[, i]))) == TRUE)
# 
#     # List all the unique errors that exist
#     classerrors <- unique(errortable[, i])
# 
#     return(classerrors)
#   }
#   else {
# 
#     # Update class
#     myData[, i] <- as.numeric(myData[, i])
# 
#     # Set change to the global environment
#     .GlobalEnv$myData[, i] <- myData[, i]
#   }
# 
#   }
